#!/usr/bin/env bash

SERVER=/Users/uday/jdt
JAR=plugins/org.eclipse.equinox.launcher_*.jar

java \
  -javaagent:/Users/uday/tools/lombok.jar \
  -Declipse.application=org.eclipse.jdt.ls.core.id1 \
  -Dosgi.bundles.defaultStartLevel=4 \
  -Declipse.product=org.eclipse.jdt.ls.core.product \
  -Dlog.protocol=true \
  -Dlog.level=ALL \
  -noverify \
  -Xms1G \
  -Xmx2G \
  -jar $SERVER/$JAR \
  -configuration $SERVER/config_mac/ \
  -data "$1" \
  --add-modules=ALL-SYSTEM \
  --add-opens java.base/java.util=ALL-UNNAMED \
  --add-opens java.base/java.lang=ALL-UNNAMED \
  "$@"

